/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Rodrigo
 */
public class frmPerdaPesoMetadeMes extends javax.swing.JFrame {
    
    Statement stat = null;
    ResultSet rs = null;                
    Connection con = null;
    
    private void CarregaMes(){
        // Esse método carrega os meses da tabela Mes
            try{
                con = DBConnection.SQL.getConnection();
                String sql = "select * from Mes";
                stat = con.createStatement();
                rs = stat.executeQuery(sql);
            
                while(rs.next()){
                    String mes = rs.getString("nome_mes").trim();
                    combo_meses.addItem(mes);
                }
            }
            catch (Exception e){
                e.printStackTrace();
            }
        }
    /**
     * Creates new form frmPerdaPesoMetadeMes
     */
    public frmPerdaPesoMetadeMes() {
        initComponents();
        CarregaMes();
    }
    private int getMesID(){
        // Esse método verifica qual mes foi selecionado e retorna o ID do mesmo
            int id_mes=0;
            try {
                con = DBConnection.SQL.getConnection();
                String sql = ("select id_mes from Mes where nome_Mes like '"+combo_meses.getSelectedItem()+"'");
                stat = con.createStatement();
                rs = stat.executeQuery(sql);
                while(rs.next()){
                    id_mes = Integer.parseInt(rs.getString("id_mes"));
                }
            }
            catch (Exception e){
                e.printStackTrace();
            }
            return id_mes;
        }
    private void mostrar(){
        // Esse método verifica qual paciente foi selecionado pela combo box e busca as informçãoes dele no Banco de dados
        int linha = 0;
        double diferenca=0;
            try {
                con = DBConnection.SQL.getConnection();
                String sql =("select Paciente.nome_paciente, Pesagem.peso_inicio, Pesagem.peso_quinzena, Mes.nome_mes, Pesagem.peso_inicio-Pesagem.peso_quinzena as 'diferenca' "+
                             " from Pesagem join Paciente on Paciente.id_paciente=Pesagem.id_paciente join Mes on Mes.id_mes=Pesagem.id_mes "+
                             " where Mes.id_mes = "+getMesID());
                stat = con.createStatement();
                rs = stat.executeQuery(sql);
                while(rs.next()){
                    diferenca = Double.parseDouble(rs.getString("diferenca"));
                    if(diferenca>0){
                        table_pacientes.setValueAt(rs.getString("nome_mes"), linha, 0);
                        table_pacientes.setValueAt(rs.getString("nome_paciente"), linha, 1);
                        table_pacientes.setValueAt(rs.getString("peso_inicio"), linha, 2);
                        table_pacientes.setValueAt(rs.getString("peso_quinzena"), linha, 3);
                        table_pacientes.setValueAt(rs.getString("diferenca"), linha, 4);
                        linha++;
                    }
                }
            }
            catch (Exception e){
                e.printStackTrace();
            }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_menu = new javax.swing.JButton();
        btn_Show = new javax.swing.JButton();
        lbl_perda_peso_quinzena = new javax.swing.JLabel();
        lbl_meses = new javax.swing.JLabel();
        combo_meses = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_pacientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perda de Peso no Inicio do Mes");
        setResizable(false);

        btn_menu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_menu.setText("Menu");
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });

        btn_Show.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Show.setText("Mostrar");
        btn_Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ShowActionPerformed(evt);
            }
        });

        lbl_perda_peso_quinzena.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_perda_peso_quinzena.setText("Perda de Peso na Primeira Metade do Mes");

        lbl_meses.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_meses.setText("Meses: ");

        combo_meses.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        table_pacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mês", "Paciente", "Peso Anterior Kg", "Peso Atual Kg", "Perdeu Kg"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_pacientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbl_perda_peso_quinzena))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lbl_meses)
                                .addGap(18, 18, 18)
                                .addComponent(combo_meses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(btn_Show, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(172, 172, 172)
                                .addComponent(btn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbl_perda_peso_quinzena)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_meses)
                    .addComponent(combo_meses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        // TODO add your handling code here:
        // Esse botão volta ao menu inicial
        this.dispose();
    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn_ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ShowActionPerformed
        // TODO add your handling code here:
        // Esse botão exibe os pacientes que perderam peso na primeira metade do Mês
        mostrar();
    }//GEN-LAST:event_btn_ShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPerdaPesoMetadeMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPerdaPesoMetadeMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPerdaPesoMetadeMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPerdaPesoMetadeMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPerdaPesoMetadeMes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Show;
    private javax.swing.JButton btn_menu;
    private javax.swing.JComboBox<String> combo_meses;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_meses;
    private javax.swing.JLabel lbl_perda_peso_quinzena;
    private javax.swing.JTable table_pacientes;
    // End of variables declaration//GEN-END:variables
}
